#env internal
# PROD
ftp.host=10.70.1.77
ftp.port=21
ftp.username=rekon
ftp.password=rekon
ftp.base.dir=/vertikal
ftp.use.tls=false <--- Tambahkan ini di PROD (Non-TLS)

# DEV
# ftp.host=10.71.1.177
# ftp.host=localhost
# ftp.port=21
# ftp.username=rekon
# ftp.password=rekon
# ftp.base.dir=/vertikal
# ftp.use.tls=true   
#<--- Tambahkan ini di DEV (Wajib TLS)