# PROD
# 202060709
# ---------------------------------------------------
db.url=jdbc:oracle:thin:@//10.70.1.2:22102/DBOLAPTRJ
db.user=OPHARTDE
db.password=B@ntuP2apst14072017

# DEV
# 202060709
# ---------------------------------------------------
# db.url=jdbc:oracle:thin:@//10.14.152.135:1521/dbdtob
# db.user=OPHARTDE
# db.password=p2apst123!